import { reactive } from "vue";
export const session=reactive({token:localStorage.getItem("ratewatch-token")||"",user:null,ready:false,toasts:[],config:{site_name:"RateWatch",admin_path:"admin",registration_open:true}});
export const adminSession=reactive({token:localStorage.getItem("ratewatch-admin-token")||"",user:null,ready:false});
export async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(session.token)headers.Authorization=`Bearer ${session.token}`;const response=await fetch(path,{...options,headers});if(response.status===204)return null;const body=await response.json().catch(()=>({error:`HTTP ${response.status}`}));if(!response.ok){if(response.status===401)logout();throw new Error(body.error||body.message||`HTTP ${response.status}`)}return body}
export function saveSession(data){session.token=data.token;session.user=data.user;localStorage.setItem("ratewatch-token",data.token)}export function logout(){session.token="";session.user=null;localStorage.removeItem("ratewatch-token")}
export async function adminApi(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(adminSession.token)headers.Authorization=`Bearer ${adminSession.token}`;const response=await fetch(path,{...options,headers});if(response.status===204)return null;const body=await response.json().catch(()=>({error:`HTTP ${response.status}`}));if(!response.ok){if(response.status===401)adminLogout();throw new Error(body.error||body.message||`HTTP ${response.status}`)}return body}
export function saveAdminSession(data){adminSession.token=data.token;adminSession.user=data.user;localStorage.setItem("ratewatch-admin-token",data.token)}export function adminLogout(){adminSession.token="";adminSession.user=null;localStorage.removeItem("ratewatch-admin-token")}
export async function bootstrapAdmin(){if(adminSession.token){try{adminSession.user=await adminApi("/api/admin/me")}catch{adminLogout()}}adminSession.ready=true}
export function toast(message,type="ok",meta={}){const id=Date.now()+Math.random(),item=typeof message==="object"?{...message,id}:{id,message,type,...meta};session.toasts.push(item);setTimeout(()=>{session.toasts=session.toasts.filter(x=>x.id!==id)},7000)}
export function dismissToast(id){session.toasts=session.toasts.filter(x=>x.id!==id)}
export async function bootstrap(){try{session.config=await api("/api/public-config")}catch{}if(session.token){try{session.user=await api("/api/me");if(session.user?.role==="admin")logout()}catch{logout()}}session.ready=true}
export function openEvents(){if(!session.token)return null;const es=new EventSource(`/api/events/stream?token=${encodeURIComponent(session.token)}`);es.addEventListener("notification",e=>{const v=JSON.parse(e.data);toast({id:Date.now()+Math.random(),message:v.detail,title:v.title,type:v.level,site_name:v.site_name,source_name:v.source_name,group_name:v.group_name})});return es}
