<template><div class="fm-page"><header class="fm-head"><div><span class="fm-kicker">运行记录</span><h1>异常与变更</h1><p>这里记录需要关注的失败、倍率变化和价格观测。正常且无变化的检查不会重复写入日志。</p></div><FmButton variant="outline" @click="load">刷新</FmButton></header>
  <div class="filters"><button v-for="f in filters" :key="f.value" :class="{active:filter===f.value}" @click="filter=f.value">{{f.label}}</button></div>
  <FmDataTable :columns="columns" :rows="visible" :loading="loading" empty-text="没有符合条件的记录">
    <template #cell-level="{row}"><FmStatusPill :variant="variant(row.level)">{{label(row.level)}}</FmStatusPill></template>
    <template #cell-context="{row}"><div><strong>{{row.site_name||'未关联站点'}}</strong><div class="muted">上游：{{row.source_name||'—'}}</div><div class="muted">分组：{{row.group_name||'—'}}</div></div></template>
    <template #cell-detail="{row}"><strong>{{row.title}}</strong><div class="muted">{{row.reason||row.detail}}</div><details v-if="row.request_id" class="log-more"><summary>查看检查编号</summary><div class="mono">{{row.request_id}}</div></details></template>
    <template #cell-change="{row}"><span v-if="row.before_rate!=null||row.after_rate!=null" class="mono">{{fmt(row.before_rate)}} → {{fmt(row.after_rate)}}</span><span v-else>—</span></template>
    <template #cell-created_at="{value}">{{date(value)}}</template>
  </FmDataTable>
</div></template>
<script setup>import{computed,onMounted,ref}from"vue";import{api,toast}from"../api/client.js";import FmButton from"../ui/freemodel/components/FmButton.vue";import FmDataTable from"../ui/freemodel/components/FmDataTable.vue";import FmStatusPill from"../ui/freemodel/components/FmStatusPill.vue";const events=ref([]),loading=ref(true),filter=ref("all"),filters=[{value:"all",label:"全部"},{value:"error",label:"失败"},{value:"warning",label:"需要留意"},{value:"success",label:"已同步"},{value:"info",label:"价格观测"}],columns=[{key:"level",label:"结果"},{key:"context",label:"站点 / 上游 / 分组"},{key:"detail",label:"详细原因"},{key:"change",label:"倍率变化"},{key:"created_at",label:"时间"}],visible=computed(()=>filter.value==="all"?events.value:events.value.filter(e=>e.level===filter.value));async function load(){loading.value=true;try{events.value=await api("/api/events")}catch(e){toast(e.message,"error")}finally{loading.value=false}}const fmt=v=>v==null?'—':Number(v).toFixed(4).replace(/0+$/,'').replace(/\.$/,''),variant=v=>({success:"ok",warning:"warn",error:"error",info:"info"}[v]||"neutral"),label=v=>({success:"已完成",warning:"需留意",error:"失败",info:"已记录"}[v]||v),date=v=>new Date(v).toLocaleString();onMounted(load);</script>
<style scoped>.filters{display:flex;gap:6px;margin-bottom:14px;flex-wrap:wrap}.filters button{padding:7px 11px;border-radius:7px;background:transparent;color:var(--fm-ink-muted);font-size:12px}.filters button.active{background:var(--fm-ink);color:var(--fm-bg)}.log-more{margin-top:6px;color:var(--fm-ink-muted);font-size:11px}.log-more summary{cursor:pointer}.log-more div{margin-top:4px}</style>
