<template><div class="fm-page">
  <header class="fm-head"><div><span class="fm-kicker">运行概览</span><h1>利润防护状态</h1><p>只显示需要关注的异常和已经发生的倍率变更，正常检查不会反复打扰你。</p></div><div class="fm-actions"><FmButton variant="outline" @click="load">刷新</FmButton><RouterLink to="/sources"><FmButton variant="primary">添加上游</FmButton></RouterLink></div></header>
  <FmStatePanel v-if="loading" state="loading"/><template v-else>
    <div class="fm-stats"><article class="fm-stat"><span class="label">我的站点</span><strong>{{stats.sites||0}}</strong><small>已连接站点</small></article><article class="fm-stat"><span class="label">可监听上游</span><strong>{{stats.sources||0}}</strong><small>正在关注价格</small></article><article class="fm-stat"><span class="label">运行中任务</span><strong>{{stats.tasks||0}}</strong><small>自动同步规则</small></article><article class="fm-stat"><span class="label">24 小时异常</span><strong>{{stats.alerts||0}}</strong><small>需要留意</small></article></div>
    <section class="section"><div class="section-head"><div><h2>系统如何工作</h2><p>不同平台会自动选择合适的倍率读取方式。</p></div></div><div class="grid-2"><article class="fm-card"><FmStatusPill variant="ok">直接读取</FmStatusPill><h3>Sub2API 上游</h3><p>使用普通 Key 直接读取当前生效倍率，不产生额外模型用量。</p></article><article class="fm-card"><FmStatusPill variant="info">定时检查</FmStatusPill><h3>New API 上游</h3><p>使用你选择的便宜文本模型发起极小请求，从实际账单确认当前倍率。</p></article></div></section>
    <section class="section"><div class="section-head"><div><h2>最近异常与变更</h2><p>清楚记录对应站点、上游、分组与失败原因。</p></div><RouterLink to="/events">查看全部</RouterLink></div><FmDataTable :columns="columns" :rows="events.slice(0,8)" empty-text="暂无异常或倍率变更"><template #cell-context="{row}">{{row.site_name||'—'}} / {{row.source_name||'—'}} / {{row.group_name||'—'}}</template><template #cell-level="{row}"><FmStatusPill :variant="variant(row.level)">{{label(row.level)}}</FmStatusPill></template><template #cell-created_at="{value}">{{date(value)}}</template></FmDataTable></section>
  </template>
</div></template>
<script setup>import{onMounted,ref}from"vue";import{api,toast}from"../api/client.js";import FmButton from"../ui/freemodel/components/FmButton.vue";import FmDataTable from"../ui/freemodel/components/FmDataTable.vue";import FmStatePanel from"../ui/freemodel/components/FmStatePanel.vue";import FmStatusPill from"../ui/freemodel/components/FmStatusPill.vue";const loading=ref(true),stats=ref({}),events=ref([]),columns=[{key:"level",label:"结果"},{key:"title",label:"事件"},{key:"context",label:"站点 / 上游 / 分组"},{key:"created_at",label:"时间"}];async function load(){loading.value=true;try{[stats.value,events.value]=await Promise.all([api("/api/dashboard"),api("/api/events")])}catch(e){toast(e.message,"error")}finally{loading.value=false}}onMounted(load);const variant=v=>({success:"ok",warning:"warn",error:"error",info:"info"}[v]||"neutral"),label=v=>({success:"已完成",warning:"需留意",error:"失败",info:"已记录"}[v]||v),date=v=>v?new Date(v).toLocaleString():"—";</script>
<style scoped>.fm-card h3{margin:14px 0 6px;font-size:16px}.fm-card p{margin:0;color:var(--fm-ink-muted);font-size:13px}</style>
